// Code generated by "stringer -type=ConfigName -trimprefix=Cfg"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CfgTest-0]
	_ = x[Max-1]
}

const _ConfigName_name = "TestMax"

var _ConfigName_index = [...]uint8{0, 4, 7}

func (i ConfigName) String() string {
	if i < 0 || i >= ConfigName(len(_ConfigName_index)-1) {
		return "ConfigName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConfigName_name[_ConfigName_index[i]:_ConfigName_index[i+1]]
}
